---
# Taken from: https://appdefensealliance.dev/casa/tier-2/ast-guide/static-scan
# as that is out of date, updated to the latest version of the scanner.
# https://help.fluidattacks.com/portal/en/kb/articles/validate-casa-tier-2-requirements
namespace: thunderbird-ios
working_dir: /repo
language: EN
output:
  file_path: /repo/fluidscan-results.sarif
  format: SARIF
sast:
  include:
    - .
  exclude:
    - glob(**/build/**)
    - glob(**/test/**)
    - glob(docs/**)
sca:
  include:
    - .
  exclude:
    - glob(**/test/**)
    - glob(docs/**)
file_size_limit: false
tracing_opt_out: true
